trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: templates
      type: git
      name: Petclinic/petclinic-pipeline-template
      ref: master-acr-sonar-cloud

variables:
  azureServiceConnection: 'Azure-Subscription-Conn'
  devAppName: 'app-petclinic-dev-4ebnal' 
  testAppName: 'app-petclinic-testing-wery5k'
  prodAppName: 'app-petclinic-prod-x7hl53'

  imageRepository: 'petclinic-app'

  # Environment-Specific ACR Variables
  devAcrConnection: 'dev-acr-service-connection'
  devAcrLoginServer: 'acrpetclinicdev4ebnal.azurecr.io'

  testAcrConnection: 'test-acr-service-connection'
  testAcrLoginServer: 'acrpetclinictestingwery5k.azurecr.io'

  prodAcrConnection: 'prod-acr-service-connection'
  prodAcrLoginServer: 'acrpetclinicprodx7hl53.azurecr.io'

  # SonarQube Variables (Replaced SonarCloud)
  sonarServiceConnection: 'sonarqube-service-connection'
  sonarProjectKey: 'petclinic'
  sonarProjectName: 'petclinic'

stages:
# --- STAGE 1: BUILD (Pushes to DEV ACR) ---
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - template: build.yaml@templates
      parameters:
        jdkVersion: '1.17'
        devAcrConnection: '$(devAcrConnection)'
        imageRepository: '$(imageRepository)'
        sonarServiceConnection: '$(sonarServiceConnection)'
        sonarProjectKey: '$(sonarProjectKey)'
        sonarProjectName: '$(sonarProjectName)'

# --- STAGE 2: DEPLOY TO DEV ---
- stage: DeployDev
  displayName: 'Deploy to Development'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: deploy.yaml@templates
    parameters:
      environmentName: 'dev'
      azureServiceConnection: '$(azureServiceConnection)'
      webAppName: '$(devAppName)'
      promoteImage: false # Image is already in Dev ACR
      targetAcrConnection: '$(devAcrConnection)'
      targetAcrLoginServer: '$(devAcrLoginServer)'
      imageRepository: '$(imageRepository)'
      imageTag: '$(Build.BuildId)'

# --- MANUAL APPROVAL: DEV -> TESTING ---
- stage: ApproveTesting
  displayName: 'Manual Approval - Promote to Testing'
  dependsOn: DeployDev
  condition: succeeded()
  jobs:
  - job: WaitForApprovalTesting
    pool: server
    timeoutInMinutes: 1440
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Please validate Dev deployment and approve promotion to Testing.'

# --- STAGE 3: DEPLOY TO TESTING (Promotes Dev ACR -> Test ACR) ---
- stage: DeployTest
  displayName: 'Deploy to Testing'
  dependsOn: ApproveTesting
  condition: succeeded()
  jobs:
  - template: deploy.yaml@templates
    parameters:
      environmentName: 'testing'
      azureServiceConnection: '$(azureServiceConnection)'
      webAppName: '$(testAppName)'
      promoteImage: true
      sourceAcrConnection: '$(devAcrConnection)'
      sourceAcrLoginServer: '$(devAcrLoginServer)'
      targetAcrConnection: '$(testAcrConnection)'
      targetAcrLoginServer: '$(testAcrLoginServer)'
      imageRepository: '$(imageRepository)'
      imageTag: '$(Build.BuildId)'

# --- MANUAL APPROVAL: TESTING -> PROD ---
- stage: ApproveProd
  displayName: 'Manual Approval - Promote to Production'
  dependsOn: DeployTest
  condition: succeeded()
  jobs:
  - job: WaitForApprovalProd
    pool: server
    timeoutInMinutes: 1440
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Please confirm Testing sign-off is complete and approve Production deployment.'

# --- STAGE 4: DEPLOY TO PROD (Promotes Test ACR -> Prod ACR) ---
- stage: DeployProd
  displayName: 'Deploy to Production'
  dependsOn: ApproveProd
  condition: succeeded()
  jobs:
  - template: deploy.yaml@templates
    parameters:
      environmentName: 'prod'
      azureServiceConnection: '$(azureServiceConnection)'
      webAppName: '$(prodAppName)'
      promoteImage: true
      sourceAcrConnection: '$(testAcrConnection)'
      sourceAcrLoginServer: '$(testAcrLoginServer)'
      targetAcrConnection: '$(prodAcrConnection)'
      targetAcrLoginServer: '$(prodAcrLoginServer)'
      imageRepository: '$(imageRepository)'
      imageTag: '$(Build.BuildId)'