trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: templates
      type: git
      name: <project-name>/petclinic-pipeline-template
      ref: main

variables:
  azureServiceConnection: 'Azure-Subscription-Conn'
  devAppName: 'app-petclinic-dev-<suffix>' 
  testAppName: 'app-petclinic-prod-<suffix>'
  prodAppName: 'app-petclinic-testing-<suffix>'

  imageRepository: 'petclinic-app'

  # Environment-Specific ACR Variables
  devAcrConnection: 'dev-acr-service-connection'
  devAcrLoginServer: '<dev-registry>.azurecr.io'

  testAcrConnection: 'test-acr-service-connection'
  testAcrLoginServer: '<test-registry>.azurecr.io'

  prodAcrConnection: 'prod-acr-service-connection'
  prodAcrLoginServer: '<prod-registry>.azurecr.io'

  # SonarCloud Variables
  sonarServiceConnection: 'sonarcloud-service-connection'
  sonarOrganization: '<your-sonar-org>'
  sonarProjectKey: '<your-sonar-project-key>'

stages:
# --- STAGE 1: BUILD ---
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - template: build.yaml@templates
      parameters:
        jdkVersion: '1.17'
        imageRepository: '$(imageRepository)'
        imageTag: '$(Build.BuildId)'
        sonarServiceConnection: '$(sonarServiceConnection)'
        sonarOrganization: '$(sonarOrganization)'
        sonarProjectKey: '$(sonarProjectKey)'

# --- STAGE 2: DEPLOY TO DEV ---
- stage: DeployDev
  displayName: 'Deploy to Development'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: deploy.yaml@templates
    parameters:
      environmentName: 'dev'
      azureServiceConnection: '$(azureServiceConnection)'
      webAppName: '$(devAppName)'
      acrServiceConnection: '$(devAcrConnection)'
      acrLoginServer: '$(devAcrLoginServer)'
      imageRepository: '$(imageRepository)'
      imageTag: '$(Build.BuildId)'

# --- MANUAL APPROVAL: DEV -> TESTING ---
- stage: ApproveTesting
  displayName: 'Manual Approval - Promote to Testing'
  dependsOn: DeployDev
  condition: succeeded()
  jobs:
  - job: WaitForApprovalTesting
    pool: server
    timeoutInMinutes: 1440
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Please validate Dev deployment and approve promotion to Testing.'

# --- STAGE 3: DEPLOY TO TESTING ---
- stage: DeployTest
  displayName: 'Deploy to Testing'
  dependsOn: ApproveTesting
  condition: succeeded()
  jobs:
  - template: deploy.yaml@templates
    parameters:
      environmentName: 'testing'
      azureServiceConnection: '$(azureServiceConnection)'
      webAppName: '$(testAppName)'
      acrServiceConnection: '$(testAcrConnection)'
      acrLoginServer: '$(testAcrLoginServer)'
      imageRepository: '$(imageRepository)'
      imageTag: '$(Build.BuildId)'

# --- MANUAL APPROVAL: TESTING -> PROD ---
- stage: ApproveProd
  displayName: 'Manual Approval - Promote to Production'
  dependsOn: DeployTest
  condition: succeeded()
  jobs:
  - job: WaitForApprovalProd
    pool: server
    timeoutInMinutes: 1440
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Please confirm Testing sign-off is complete and approve Production deployment.'

# --- STAGE 4: DEPLOY TO PROD ---
- stage: DeployProd
  displayName: 'Deploy to Production'
  dependsOn: ApproveProd
  condition: succeeded()
  jobs:
  - template: deploy.yaml@templates
    parameters:
      environmentName: 'prod'
      azureServiceConnection: '$(azureServiceConnection)'
      webAppName: '$(prodAppName)'
      acrServiceConnection: '$(prodAcrConnection)'
      acrLoginServer: '$(prodAcrLoginServer)'
      imageRepository: '$(imageRepository)'
      imageTag: '$(Build.BuildId)'
